# Site settings
title: Znow
email: znowm4n@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://znow.github.io" # the base hostname & protocol for your site
twitter_username: daniel_wg
github_username:  Znow
host: 0.0.0.0

# Build settings
markdown: kramdown
highlighter: pygments
permalink:   date

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: true
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 'UA-60138109-1'
  getclicky :
    site_id :
