# Site settings
title: Znow
email: znowm4n@gmail.com
description: > # this means to ignore newlines until "baseurl:"
comments: true

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.znow.dk" # the base hostname & protocol for your site
twitter_username: daniel_wg
github_username:  Znow
host: 0.0.0.0

# Build settings
markdown: kramdown
highlighter: pygments
permalink:   date

kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers:

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 'UA-60138109-1'
  getclicky :
    site_id :
